### PR TITLE
Minesweeper & Instances

### PR DESCRIPTION
**Pull request by RubenJ01**
@gaborszita could you take a look at the new instance management system I created when you find the time?
I've made it very easy for other games to implement this system but the only downside I can think of is that it only allows the user to play 1 game at a time. I don't think this is a big issue tho since users playing multiple games at the same time does not make much sense anyways.

### CODE REVIEW

**Review by gaborszita — CHANGES_REQUESTED** [review]
Seems good, one small thing:
Do you need the jpg files in the boards folder (e.g. mindsweeper4136f95b.png)? It seems to me that they were only left there by mistake.

**Comment by RubenJ01** [comment]
> Seems good, one small thing: Do you need the jpg files in the boards folder (e.g. mindsweeper4136f95b.png)? It seems to me that they were only left there by mistake.

Il remove those, didnt notice those were left in.

**Comment by RubenJ01** [comment]
@gaborszita they should be removed now, is this ready to merge?

**Comment by gaborszita** [comment]
Yeah, go for it.
-------- Original message --------From: Ruben Eekhof ***@***.***> Date: 1/5/23  4:48 PM  (GMT+01:00) To: MiloBotDev/MiloBot ***@***.***> Cc: Gabor Szita ***@***.***>, Mention ***@***.***> Subject: Re: [MiloBotDev/MiloBot] Minesweeper & Instances (PR #90) 
@gaborszita they should be removed now, is this ready to merge?

**Pull request merged**
